
export const products = [

    {
        id: 1,
        title: "Nike World",
        subtitle: "Running Shoes Absorbing Air",
        price: 15000,
        secondUnit: "",
        stock: 12,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        detail: {
            size: ["s", "m", "l"],
            color: ["red", "blue", "green"],
        },
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617920/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_59_jt0ger.png",
    },

    {
        id: 2,
        title: "Wilson Advance",
        subtitle: "White Comfy Urban Shoes",
        price: 14500,
        secondUnit: "",
        stock: 5,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617920/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h08_59_t8f2sr.png",
        discount:"",
    },

    {
        id: 3,
        title: "Nike Black",
        subtitle: "Elegant Sportsy Shoes",
        price: 19000,
        secondUnit: "",
        stock: 4,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617920/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_32_ljzvbd.png"
    },

    {
        id: 4,
        title: "Nike Run 100",
        subtitle: "Run With style",
        price: 17800,
        secondUnit: "",
        stock: 8,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617920/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h05_46_adkgyc.png"
    },
    {
        id: 5,
        title: "Nike Run 360",
        subtitle: "Best Running Shoes",
        price: 12300,
        secondUnit: "",
        stock: 16,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617920/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h05_16_pwh9qe.png"
    },
    {
        id: 6,
        title: "Nike Armor",
        subtitle: "Men's training Basketball Shoes",
        price: 15900,
        secondUnit: "",
        stock: 11,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617920/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h04_03_d075k5.png"
    },
    {
        id: 7,
        title: "Nike Velvet",
        subtitle: "Urban Sportsy Style",
        price: 22000,
        discount: "8",
        secondUnit: "",
        stock: 7,
        category: "shoes",
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617920/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h07_00_oaxfd9.png",
    },
    {
        id: 8,
        title: "Air Jordan 120",
        subtitle: "Jordan Shoes to Fly Higher",
        price: 24000,
        discount: "12",
        secondUnit: "",
        stock: 8,
        category: "shoes",
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617919/web%20access/samples%20for%20e-commerce/Shoes/2023-07-17_15h06_21_tcgjsp.png",
    },
    {
        id: 11,
        title: "Easy Care",
        subtitle: "Comfortable Elastic Pants",
        price: 11000,
        secondUnit: "",
        stock: 3,
        description: "Pantalon largo elastizados para mayor comodidad ",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617955/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h00_17_waukiw.png"
    },
    {
        id: 12,
        title: "Henley",
        subtitle: "Green Elegant Shorts",
        price: 18000,
        secondUnit: "",
        stock: 12,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617954/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_14h59_40_nfj0yg.png"
    },
    {
        id: 13,
        title: "Top Nike Halter",
        subtitle: "Cotton Long Pants",
        price: 17300,
        secondUnit: "",
        stock: 3,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617953/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_14h54_01_nysl3o.png"
    },
    {
        id: 14,
        title: "Onesie West",
        subtitle: "Sport Pants for Men",
        price: 13200,
        secondUnit: "",
        stock: 2,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617953/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_14h54_17_sjtv5j.png"
    },
    {
        id: 15,
        title: "Ringer Long",
        subtitle: "Best for windy day",
        price: 14800,
        secondUnit: "",
        stock: 12,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617952/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_14h54_53_k2jnq4.png"
    },
    {
        id: 16,
        title: "Pano 360",
        subtitle: "Elegant Pants for Men",
        price: 14900,
        secondUnit: "",
        stock: 18,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617952/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h01_49_ea8f8u.png"
    },
    {
        id: 17,
        title: "Pano Sport Nike",
        subtitle: "Elegant Sports Pants for Men",
        price: 14900,
        discount: "9",
        secondUnit: "",
        stock: 18,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617952/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_14h54_34_gke8nv.png"
    },
    {
        id: 18,
        title: "Pano Short",
        subtitle: "Red Elegant Shorts",
        price: 14900,
        discount: "15",
        secondUnit: "",
        stock: 18,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617953/web%20access/samples%20for%20e-commerce/Pants/2023-07-17_15h01_06_kffks9.png"
    },
    {
        id: 21,
        title: "Easy Care",
        subtitle: "Black Cool Shirt for Men",
        price: 11900,
        secondUnit: "",
        stock: 10,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617879/web%20access/samples%20for%20e-commerce/Shirts/2023-07-17_15h11_49_t8mty2.png"
    },
    {
        id: 22,
        title: "Henley Shirt",
        subtitle: "Red Shirt for Men",
        price: 18100,
        secondUnit: "",
        stock: 3,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617879/web%20access/samples%20for%20e-commerce/Shirts/2023-07-17_15h11_03_tsm1yc.png"
    },
    {
        id: 23,
        title: "Top Halter Roll",
        subtitle: "Elegant Sports Short Sleeves",
        price: 13000,
        secondUnit: "",
        stock: 2,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617878/web%20access/samples%20for%20e-commerce/Shirts/2023-07-17_15h10_26_kt4ihx.png"
    },
    {
        id: 24,
        title: "Onesie Dose Sport",
        subtitle: "White-green Long Sleeves for Sport",
        price: 15100,
        secondUnit: "",
        stock: 6,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617878/web%20access/samples%20for%20e-commerce/Shirts/2023-07-17_15h13_13_kffcna.png"
    },
    {
        id: 25,
        title: "Ringer Inner 360",
        subtitle: "Green Sweat-Shirt",
        price: 9800,
        secondUnit: "",
        stock: 9,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617878/web%20access/samples%20for%20e-commerce/Shirts/2023-07-17_15h16_31_fsvmlp.png",
    },
    {
        id: 26,
        title: "Nike Blue Elegant",
        subtitle: "Blue Cotton Short Sleeves",
        price: 16600,
        secondUnit: "",
        stock: 4,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617878/web%20access/samples%20for%20e-commerce/Shirts/2023-07-17_15h15_07_kebc8t.png"
    },
    {
        id: 27,
        title: "Nike Shirt",
        subtitle: "Brown Cotton Short Sleeves",
        price: 16600,
        discount: "5",
        secondUnit: "",
        stock: 4,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617878/web%20access/samples%20for%20e-commerce/Shirts/2023-07-17_15h12_24_oqwnio.png"
    },
    {
        id: 28,
        title: "Nike Jordan",
        subtitle: "White Cotton Short Sleeves",
        price: 16600,
        discount: "10",
        secondUnit: "",
        stock: 4,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689617878/web%20access/samples%20for%20e-commerce/Shirts/2023-07-17_15h14_17_y578w6.png"
    },
]
