
export const products = [

    {
        id: 1,
        title: "Nike 360",
        subtitle: "Running Shoes Absorbing Air",
        price: 15000,
        secondUnit: "",
        stock: 12,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686681924/samples/ecommerce/Zapatillas/zapas1_ywv3ql.png"
    },

    {
        id: 2,
        title: "Wilson Advance",
        subtitle: "White Comfy Urban Shoes",
        price: 14500,
        secondUnit: "",
        stock: 5,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686681924/samples/ecommerce/Zapatillas/zapas4_w7xyyx.png"
    },

    {
        id: 3,
        title: "Puma Black",
        subtitle: "Elegant Sportsy Shoes",
        price: 19000,
        secondUnit: "",
        stock: 4,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686939819/samples/ecommerce/Zapatillas/zapas33_jfyxes.png"
    },

    {
        id: 4,
        title: "Reebok Run 100",
        subtitle: "Jogging With style",
        price: 17800,
        secondUnit: "",
        stock: 8,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686681924/samples/ecommerce/Zapatillas/zapas2_tyqtg3.png"
    },
    {
        id: 5,
        title: "Kappa Run",
        subtitle: "Best Running Shoes",
        price: 12300,
        secondUnit: "",
        stock: 16,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1685736166/samples/ecommerce/shoes.png"
    },
    {
        id: 6,
        title: "Nike Armor",
        subtitle: "Men's training Basketball Shoes",
        price: 15900,
        secondUnit: "",
        stock: 11,
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        category: "shoes",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686940793/samples/ecommerce/Zapatillas/zapas66_kseevr.png"
    },
    {
        id: 7,
        title: "Nike Velvet",
        subtitle: "Urban Sportsy Style",
        price: 22000,
        secondUnit: "",
        stock: 7,
        category: "shoes",
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689465846/samples/ecommerce/Zapatillas/2023-07-15_20h14_45-removebg-preview_c2p1nt.png",
    },
    {
        id: 9,
        title: "Air Jordan 120",
        subtitle: "Jordan Shoes to Fly Highe",
        price: 24000,
        secondUnit: "",
        stock: 8,
        category: "shoes",
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689465846/samples/ecommerce/Zapatillas/2023-07-15_20h13_58-removebg-preview_cwvq1j.png",
    },
    {
        id: 7,
        title: "Nike Velvet",
        subtitle: "Urban Sportsy Style",
        price: 22000,
        secondUnit: "",
        stock: 7,
        category: "shoes",
        description: "Step up your style game with our exclusive limited edition shoes, designed for comfort and crafted with premium materials. Don't miss out on this irresistible sale!",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689465846/samples/ecommerce/Zapatillas/2023-07-15_20h14_45-removebg-preview_c2p1nt.png",
    },
    {
        id: 11,
        title: "Easy Care",
        subtitle: "Comfortable Elastic Pants",
        price: 11000,
        secondUnit: "",
        stock: 3,
        description: "Pantalon largo elastizados para mayor comodidad ",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757052/samples/ecommerce/Pantalones/pantalon1-removebg-preview_ncltas.png"
    },
    {
        id: 12,
        title: "Henley",
        subtitle: "Blue Elegant Shorts",
        price: 18000,
        secondUnit: "",
        stock: 12,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757053/samples/ecommerce/Pantalones/pantalon5-removebg-preview_sgxsk6.png"
    },
    {
        id: 13,
        title: "Top Halter",
        subtitle: "Cotton Long Pants",
        price: 17300,
        secondUnit: "",
        stock: 3,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757052/samples/ecommerce/Pantalones/pantalon2-removebg-preview_qasuzd.png"
    },
    {
        id: 14,
        title: "Onesie West",
        subtitle: "Military Cargo Stylish Pants",
        price: 13200,
        secondUnit: "",
        stock: 2,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757052/samples/ecommerce/Pantalones/pantalon3-removebg-preview_bsucmh.png"
    },
    {
        id: 15,
        title: "Ringer Long",
        subtitle: "Long Extra Side Pockets",
        price: 14800,
        secondUnit: "",
        stock: 12,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757052/samples/ecommerce/Pantalones/pantalon4-removebg-preview_gpphsl.png"
    },
    {
        id: 16,
        title: "Pano Short",
        subtitle: "Dressing Elegant Shorts",
        price: 14900,
        secondUnit: "",
        stock: 18,
        description: "Experience unrivaled comfort and style with our 'FlexFit' pants. Designed for ultimate flexibility, these modern slim-fit pants redefine your wardrobe with effortless versatility and superior craftsmanship.",
        category: "pants",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757052/samples/ecommerce/Pantalones/pantalon6-removebg-preview_g8zqdf.png"
    },
    {
        id: 20,
        title: "Camisa Rustica",
        subtitle: "Rustica con elegancia",
        secondUnit: "",
        stock: 9,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689532801/samples/ecommerce/Camisas/2023-07-16_15h37_27-removebg-preview_rfy6ka.png"
    },
    {
        id: 21,
        title: "Easy Care Long",
        subtitle: "Blue Cotton Long Sleeves",
        price: 11900,
        secondUnit: "",
        stock: 10,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757086/samples/ecommerce/Camisas/camisa2-removebg-preview_ga3u34.png"
    },
    {
        id: 22,
        title: "Henley Shirt",
        subtitle: "Green Shirt Long Sleeves",
        price: 18100,
        secondUnit: "",
        stock: 3,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757086/samples/ecommerce/Camisas/camisa4-removebg-preview_sjqcl2.png"
    },
    {
        id: 23,
        title: "Top Halter Roll",
        subtitle: "Elegant Sports Long Sleeves",
        price: 13000,
        secondUnit: "",
        stock: 2,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757085/samples/ecommerce/Camisas/camisa6-removebg-preview_1_aavphg.png"
    },
    {
        id: 24,
        title: "Onesie Dose",
        subtitle: "Blue Short Sleeves",
        price: 15100,
        secondUnit: "",
        stock: 6,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757085/samples/ecommerce/Camisas/camisa1-removebg-preview_unk7t9.png"
    },
    {
        id: 25,
        title: "Ringer Inner",
        subtitle: "Red Farmer's Shirt",
        price: 9800,
        secondUnit: "",
        stock: 9,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757085/samples/ecommerce/Camisas/camisa5-removebg-preview_df3gxq.png",
    },
    {
        id: 26,
        title: "Polo Shirt",
        subtitle: "Pink Cotton Long Sleeves",
        price: 16600,
        secondUnit: "",
        stock: 4,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1686757085/samples/ecommerce/Camisas/camisa3-removebg-preview_tex1rh.png"
    },
    {
        id: 27,
        title: "Red Shem",
        subtitle: "Camisa Roja Rustica",
        price: 18600,
        secondUnit: "",
        stock: 6,
        description: "Introducing our 'Signature Series' shirt. Crafted with premium fabric, meticulous attention to detail, and a tailored fit, it exudes confidence and elevates your personal style with timeless sophistication.",
        category: "shirts",
        img: "https://res.cloudinary.com/derdim3m6/image/upload/v1689532801/samples/ecommerce/Camisas/2023-07-16_15h37_41-removebg-preview_imjtc6.png"
    },

]